replicas: 1

ingress:
  enabled: true
  port: 80

pod:
  name: flask-aws-monitor
  image: "sm1986/flask-aws-monitor"
  tag: "latest"
  targetPort: 80
  port: 5001

awsSecretName: aws-credentials

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"