replicas: 2

ingress:
  enabled: true
  path: /

pod:
  targetPort: 5001
  port: 80

awsSecretName: aws-monitor-secret

externalSecret:
  enabled: false
  secretStoreName: aws-secret-store
  region: us-east-1
  awsSecretManagerName: aws-monitor

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeralStorage: "100Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeralStorage: "1Gi"

hpa:
  enabled: true
  maxReplicas: 10
  avgCPUUtilization: 50
  avgMemoryUtilization: 50

networkPolicy:
  enabled: true

pdb:
  minAvaliableReplicas: 2

monitoring:
  namespace: monitoring

podMonitor:
  enabled: true
  path: /
  interval: 15s
  scrapeTimeout: 10s