replicas: 1

ingress:
  enabled: true

pod:
  name: flask-aws-monitor
  image: "sm1986/flask-aws-monitor"
  tag: "latest"
  targetPort: 5001
  port: 5001

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"