apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
    {{- include "exam.labels" . | nindent 4}}
spec:  
  selector: 
    matchLabels:
      app: {{ .Release.Name }}
      {{- include "exam.labels" . | nindent 6}}
  {{ if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicas }}
  {{ end }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- include "exam.labels" . | nindent 8}}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.pod.image}}:{{ .Values.pod.tag }}
        imagePullPolicy: Always

        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.pod.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket: # validate if pod alive via tcp connection
            port: {{ .Values.pod.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 20

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          privileged: false
          capabilities:
            drop:
              - ALL
        ports:
        - name: http 
          containerPort: {{ .Values.pod.targetPort }}
        
        {{ if not .Values.externalSecret.enabled }}
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.awsSecretName }}
                key: AWS_ACCESS_KEY_ID

          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.awsSecretName }}
                key: AWS_SECRET_ACCESS_KEY
        {{ end }}

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}
            ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage | quote }}

          limits:
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}
            ephemeral-storage: {{ .Values.resources.limits.ephemeralStorage | quote }}