apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
    {{- include "exam.labels" . | nindent 4}}
spec:
  selector: 
    matchLabels:
      app: {{ .Release.Name }}
      {{- include "exam.labels" . | nindent 6}}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- include "exam.labels" . | nindent 8}}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.pod.image}}:{{ .Values.pod.tag }}
        ports:
        - containerPort: {{ .Values.pod.targetPort }}
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.awsSecretName }}
                key: AWS_ACCESS_KEY_ID

          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.awsSecretName }}
                key: AWS_SECRET_ACCESS_KEY


        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}

          limits:
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}