{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-pm
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "exam.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  podMetricsEndpoints:
    - port: 
        name: http
      path: {{ .Values.monitoring.podMonitor.path }}
      interval: {{ .Values.monitoring.podMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.podMonitor.scrapeTimeout }}
{{- end }}