{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-eso-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-eso-creds
            key: secret-access-key
{{- end }}