kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}    
    {{- include "exam.labels" . | nindent 4}}
  {{ if .Values.ingress.enabled }}
  type: ClusterIP
  {{ else }}
  type: LoadBalancer
  {{ end }}
  ports:         
  - name: http   
    protocol: TCP
    {{ if .Values.ingress.enabled }}
    port: 80
    {{ end }}
    port: {{ .Values.pod.port }}
    targetPort: {{ .Values.pod.targetPort }}
