replicaCount: 2

pod:
  name: flask-aws-monitor
  image:
    name: sm1986/flask-aws-monitor
    tag: latest
  targetPort: 5001

aws:
  accessKey: ""
  secretKey: ""

service:
  port: 5001

ingress:
  enabled: false