name: alert-workflow
on:
  workflow_run:
    workflows: ["main-workflow"]
    types:
      - completed
  
jobs:
  alert-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
    - name: notify
      uses: slackapi/slack-github-action@v3.0.3
      with:
        webhook: ${{ secrets.SLACK_API}}
        webhook-type: incoming-webhook
        payload: |
          text: "Pipe line in workflow: ${{ github.event.workflow_run.name }} failed, please check the logs"
  alert-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: notify
      uses: slackapi/slack-github-action@v3.0.3
      with:
        webhook: ${{ secrets.SLACK_API}}
        webhook-type: incoming-webhook
        payload: |
          text: "Pipe line in workflow: ${{ github.event.workflow_run.name }} succeeded"