name: hello-newapp

on:
  push:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      name: checkout  
      with:
        sparse-checkout: |
          .github
          chart
    - name: notify
      run: curl -X POST -H 'Content-type: application/json' --data '{"text":"Pipe line finished successfuly"}' ${{ secrets.SLACK_API }}
