name: main-workflow

on:
  push:
  workflow_dispatch:

env:
  APP_NAME: hello-newapp

jobs:
  checkout-and-dockerize:
    runs-on: ubuntu-latest
    environment: DOCKERHUB_USERNAME

    steps:
    - name: checkout
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          .github
          chart
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.run_number }}
          ${{ vars.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest

    # - name: notify
    #   uses: slackapi/slack-github-action@v3.0.3
    #   with:
    #     webhook: ${{ secrets.SLACK_API}}
    #     webhook-type: incoming-webhook
    #     payload: |
    #       text: "Pipe line finished successfuly"

---

name: alert-workflow

on:
  workflow_run:
    workflows:
      - main-workflow
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo ${{ github.event.workflow_run.conclusion }}
        echo ${{ github.event.workflow_run.conclusion == 'failure' }}
